import = 모듈을 불러올 때 사용하는 것 (C의 #include와 유사)

import numpy as np

= numpy라는 모듈을 불러올 때 np라는 약어를 사용할 것임

In [10]:
import array
L = list(range(10))
A = array.array('i', L)
A


array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

list = 원소의 자료형이 자유료움

array = 원소의 자료형이 고정되어있다.

np.~ = 전부 배열형식으로 저장
    
    => 즉, np에 존재하는 function은 반환값이 모두 fixed-type array

np.array = 배열 제작
* array에서 정수와 실수가 혼합되면 upcast
* upcast : 더 큰 자료형으로 통일화

(만약 float과 int형을 array에 넣게되면 float>int 이므로 float으로 통일)

np.zeros(n, dtype) = (행,열)이 n자리에 갈 수 있음.

그리고 zeros 는 n만큼 0으로 채우는 것

np.ones 가 1로 채우는 것

np.full(n, x) = n 만큼 x로 가득 채우는 것

np.arange(start, last, distance)

np.linspace(start, last, 등분 기준)

np.random.random(row,colums) = 0과 1 사이의 숫자를 무작위 출력

    ==> 특정 규칙을 가지고있음
    ==> 해결방안) seed 사용
    * np.random.seed(n)
        - n을 대입하게되면 그 값은 항상 같은 random값을 반환
        - 이를 해결하려면 빈 칸으로 두면 됨.
        - 빈칸으로 실행 시, 시간값을 변수로 가지게 됨.
            * 시스템시간은 import timne , time.time() 을 통해서 구함.

np.random.normal(평균, 표준편차, (row, colums))

np.random.randint(start, last, (row, colums))

np.eye(n) = 대각선

np.empty(size) = size만큼 공간만 할당.(empty 값은 컴퓨터에 따라 다르게 초기화)

.ndim = the number of dimensions. 배열의 차원 수 or 배열의 축 수

.shape = 배열 각 차원의 크기를 튜플 형태로 표현.(n행 m열) = (n, m)

.size = 배열의 크기

.itemsize = 배열 원소 하나의 크기를 바이트로 표현

.nbytes = 배열 전체 크기를 bytes로 반환 ==> itemsize x size

In [11]:
import numpy as np
np.array([1,4,2,5,3])
np.array([3.14, 4, 3])
np.array([1,3,4], dtype='float32')
np.array([range(i, i+3) for i in [2,4,6]])
np.zeros(10, dtype=int)
np.ones((3,5), dtype=float)
np.zeros((3,2,4), dtype=int)
np.full((3,5), 3.14)
np.arange(0,20, 2)
np.linspace(0,1,5)
np.random.random((3,3))
np.random.normal((3,3))
np.random.randint(0, 10, (3,3))
np.eye(3)
np.empty(3)

array([3.14, 4.  , 3.  ])

## INDEXING

배열에 있는 원소에 붙는 번호

0에서부터 시작 n-1 까지.

그리고 n-1번째 = -1 로 표현 가능

그럼 n-2 번째 = -2 로 표현

list가 아닌 array인 경우, 하나의 데이터형만을 저장한다.

그래서 정수형 array에 특정 인덱스에 접근해서 float형으로 변경하면 정보 손실이 발생한다
    => 아래의 예시를 보면 1이 3.14로 변경되어야 하는데, 3으로 변경되었다.
    이는, array가 fixed-type이라서 그런 것이다.
    또한, .14가 손실되는 정보 손실을 확인할 수 있다.

## Slicing

array[start:last:distance(step)]

    - 공백으로 남겨두면 각각의 끝을 나타냄
        => 즉, start 가 공백이면 0번부터, last 가 공백이면 마지막 인덱스
    
    - distace가 공백이면 없는 것과 같다.

distance(step)이 음수이면 역순 array를 생성. start와 last가 서로 바뀜

다차원 배열의 경우 '","'를 이용하여 차원 구분

## SubArrays

Sub에 원본 파일을 slice해서 가져오고,

이후 Sub에서 값을 수정하면 원본 값도 변경이 된다.
    ==> 만약, 원본에 영향을 주지 않고 실험을 해보고 싶으면,
    Sub = 원본([~:~, ~:~]).copy() 를 사용하면 완전 복사된다.


## Reshaping

처음 선언한 배열의 형태(row,colums)을 새롭게 지정하는 것이다.

np.newaxis = 차원을 하나 증가시킨다.

    ==> axis가 차원, 축을 의미(in python)
    * x.reshpae((row,colums)) = 차원 여러 개 증감 가능
    * x[np.newaxis, :] = 차원 하나 증가만 가능
        - x[row, colums] 형식이고,
        - row 자리에 np.newaxis가 들어가면 행 차원이 증가
        - colums 자리에 np.newaxis가 들어가면 열 차원이 증가


In [10]:
# 정보 손실 example
x = np.array([1,2,3,4])
x[0] = 3.14
x

array([3, 2, 3, 4])

In [21]:
a = np.arange(1,10)
a[np.newaxis, :]

array([[1, 2, 3, 4]])

In [19]:
x[:, np.newaxis]

array([[1],
       [2],
       [3],
       [4]])

1차원 = 직선
2차원 = 평면
3차원 = 입체도형
reshape를 이용하여 차원 변경 가능

In [12]:
test = np.arange(1,7)
test.reshape(3,-1)
# reshape에 -1이 들어가면 그 값은 추론됨.

array([[1, 2],
       [3, 4],
       [5, 6]])