In [1]:
import numpy as np

We can use built-in array module.

The built-in means, we don't need to download and install it. Because, it comes with native Python.

* What is Ndarray 

The ndarray is N-dimension array.

Differnece between Ndarray and list is the elements data-type.

The List is Dynamic-type array, so, It can use various data type.

But, The ndarray is can use only one data type.

In [2]:
np.array([1, 4, 2, 5, 3])
# This command is create Numpy array from Python list.
# And, I have to remember this form.
# array is method, so we have to use ().
# And, np.array is from Python list, so, we have to write list-form in ().

array([1, 4, 2, 5, 3])

* range(a,b)

This mean return integer from a to b-1.


In [3]:
np.array([range(i, i+3) for i in [2,4,6]])
# We can make multi-dimension array.
# And we have to use list-comprehension, because, use memory efficiently.

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

np.arange is similar to the built in range() function.

np.arange() can use this form.

But, range() can't use np.range().

This have to use like this. np.array(range())


In [10]:
x = np.arange(1,10)
y = np.array(range(1,10))
print(x)
print(y)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In numpy, the sub_array is not new copy data.

In other words, when we slice the data in sub_array, the original array is changed too.

Defualt : The normal form. 특정한 어떤 것으로 지정해서 변경가능하나, 우리가 특정 값을 지정하지 않았을 때 사용되는 기본형을 default 값이라고 함.