# Aggregations: Min, Max, and Everything In Between

데이터에서 특징값이나 대표값을 계산하는 것은 매우 빈번하다.
 - 평균, 표준편차
 - 최소값, 최대값, 중간값, 분위값 등

NumPy는 그러한 계산을 위한 built-in  function들을 제공한다. 

## Summing the Values in an Array


In [1]:
import numpy as np

In [2]:
L = np.random.random(100)
sum(L)

54.04770284992633

NumPy 패키지의 ``sum`` 함수를 똑같이 사용할 수 있다.

In [3]:
np.sum(L) # fixed 타입을 고려하여 만든 ufunction이기에 좀 더 효율적이다

54.04770284992636

그러나 NumPy version 이 훨씬 빠르다.

In [4]:
big_array = np.random.rand(10000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

1 loop, best of 5: 851 ms per loop
100 loops, best of 5: 6.89 ms per loop


## Minimum and Maximum

Python built-in function인 ``min``과  ``max``를 통해 최소값과 최대값을 구할 수 있다. 

In [5]:
min(big_array), max(big_array)

(4.977736944855593e-08, 0.9999999276794169)

마찬가지로 NumPy version이 존재하며 더 빠르다. 

In [6]:
np.min(big_array), np.max(big_array)

(4.977736944855593e-08, 0.9999999276794169)

In [7]:
%timeit min(big_array)
%timeit np.min(big_array)

1 loop, best of 5: 622 ms per loop
100 loops, best of 5: 7.04 ms per loop


Object method를 호출하는 형태도 가능하다.

In [8]:
print(big_array.min(), big_array.max(), big_array.sum()) # big_array.min 형태나 np.min(bit_array) 값은 동일. 하지만, 표기법에 차이가 있는 경우가 있다.
# 위 같은 경우는 두가지 형태가 모두 존재하는 경우일 뿐이다.
%timeit big_array.min()

4.977736944855593e-08 0.9999999276794169 5000361.250730141
100 loops, best of 5: 6.81 ms per loop


### Multi dimensional aggregates

Muti-dimensional array에서도 가능하며, row 혹은 column 단위 적용에도 유용하다. 

In [9]:
M = np.random.random((3, 4))
print(M)

[[0.39740941 0.94403362 0.17930398 0.98495821]
 [0.63367494 0.4585507  0.88408654 0.87574895]
 [0.66351951 0.85714564 0.1686532  0.0720759 ]]


In [10]:
M.sum()

7.119160614414004

*axis* argument를 통해 축을 지정할 수 있다. 

In [11]:
M.min(axis=0)

array([0.39740941, 0.4585507 , 0.1686532 , 0.0720759 ])

In [12]:
M.max(axis=1)

array([0.98495821, 0.88408654, 0.85714564])

In [13]:
X=np.random.random((3,4,5))
print(X)
print(X.min(axis=0))
print(X.min(axis=2))

[[[0.18259386 0.23048467 0.46345384 0.33971538 0.98270121]
  [0.58826783 0.04366229 0.27610654 0.13043111 0.18725799]
  [0.91003655 0.81792637 0.81082096 0.33304238 0.4995542 ]
  [0.98643948 0.69774917 0.86205581 0.70095282 0.47316495]]

 [[0.02461422 0.13750281 0.8557727  0.86954921 0.57969417]
  [0.05450669 0.31872162 0.71466384 0.12053934 0.36505203]
  [0.99651505 0.41159385 0.54043408 0.54186823 0.49629951]
  [0.34650072 0.42387509 0.85974817 0.47878682 0.8495883 ]]

 [[0.16030506 0.52372794 0.33377764 0.93165069 0.41254818]
  [0.86325951 0.58362228 0.55736164 0.75772892 0.67260341]
  [0.13349093 0.06121698 0.12896439 0.23646022 0.76810347]
  [0.4629631  0.38145707 0.77208558 0.85051078 0.53678207]]]
[[0.02461422 0.13750281 0.33377764 0.33971538 0.41254818]
 [0.05450669 0.04366229 0.27610654 0.12053934 0.18725799]
 [0.13349093 0.06121698 0.12896439 0.23646022 0.49629951]
 [0.34650072 0.38145707 0.77208558 0.47878682 0.47316495]]
[[0.18259386 0.04366229 0.33304238 0.47316495]
 [0.02

### Other aggregation functions


|Function Name      |   NaN-safe Version  | Description                                   |
|-------------------|---------------------|-----------------------------------------------|
| ``np.sum``        | ``np.nansum``       | Compute sum of elements                       |
| ``np.prod``       | ``np.nanprod``      | Compute product of elements                   |
| ``np.mean``       | ``np.nanmean``      | Compute mean of elements                      |
| ``np.std``        | ``np.nanstd``       | Compute standard deviation                    |
| ``np.var``        | ``np.nanvar``       | Compute variance                              |
| ``np.min``        | ``np.nanmin``       | Find minimum value                            |
| ``np.max``        | ``np.nanmax``       | Find maximum value                            |
| ``np.argmin``     | ``np.nanargmin``    | Find index of minimum value                   |
| ``np.argmax``     | ``np.nanargmax``    | Find index of maximum value                   |
| ``np.median``     | ``np.nanmedian``    | Compute median of elements                    |
| ``np.percentile`` | ``np.nanpercentile``| Compute rank-based statistics of elements     |
| ``np.any``        | N/A                 | Evaluate whether any elements are true        |
| ``np.all``        | N/A                 | Evaluate whether all elements are true        |

