# HW01 <font color=red>(제출기한-3월24일 목요일 자정)</font>
---
NumPy 이해도 평가를 위한 문제입니다. 
- Loop를 사용하면 감점입니다. (즉, ufunc을 활용할 것)

> 작성방법 

- 반드시 수업시간 배운 내용만을 사용하여 코드를 작성합니다. 
- 답안은 <font color=red>'답안을 작성하시오'</font>라고 적힌 한 코드셀 내에 작성하며 여러줄로 작성해도 무방합니다.
- 출력결과가 미리 제시된 셀(<font color=red>'수정하지 마시오'</font>라고 표시된 셀)을 참고하여 코드를 작성하시오. 
- <font color=red>'수정하지 마시오'</font>라고 적힌 코드 셀은 절대로 지우면 안 됩니다.
- <font color=red> 불필요한 출력을 하는 코드</font>를 작성하면 0점 처리됩니다.
- Table에 관한 문제는 특별한 언급이 없을 경우 <font color=red> row와 column 순서가 출력 결과 예시와 동일</font>하게 합니다. 

> 제출방법

- ULMS HW1 제출란에 <font color=red>'HW01-학번.ipynb'</font>(본인학번)을 기한내 업로드합니다.


### 가정
- 아래에서 생성된 _score_ 변수는 $50 \times 5$ 크기의 2차원 numpy array이다. 
- 이는 50명 학생의 국어, 영어, 수학, 과학, 사회 점수(1번째부터 5번째 열 순서)를 각각 나타낸다. (0점~100점)

In [ ]:
### 수정하지 마시오.
import numpy as np
rng=np.random.RandomState(123)
score=rng.randint(20, 101,(50,5))
score

array([[ 86,  37,  77,  67,  93],
       [ 52,  66,  45,  98,  56],
       [100,  88,  69,  75,  87],
       [ 22,  59,  86,  67,  81],
       [ 68,  27,  72,  47,  54],
       [ 96,  60,  23,  89,  84],
       [ 95,  54,  78,  30,  42],
       [ 97,  38,  35,  47,  50],
       [ 72,  90,  46, 100,  26],
       [ 34,  95,  74,  91,  21],
       [ 63,  78,  75,  45,  70],
       [ 76,  69,  32,  38,  21],
       [ 71,  64,  68,  76,  69],
       [ 23,  87,  31,  41,  23],
       [ 31,  23,  26,  29,  34],
       [ 90,  32,  74,  47,  58],
       [ 37,  81,  94,  85,  67],
       [ 36,  25,  66,  35,  79],
       [ 60,  45,  65,  69,  20],
       [ 55,  49,  21,  88,  50],
       [ 27,  80,  85,  96,  87],
       [ 64,  71,  27,  90,  33],
       [ 48,  83,  56,  60,  83],
       [ 78,  97,  28,  98,  26],
       [ 85,  90,  60,  94,  96],
       [ 96,  45,  27,  33,  64],
       [ 21,  61,  98,  76,  83],
       [ 23,  37,  89,  70,  22],
       [ 38,  66,  65,  77,  55],
       [ 38,  

### 문제1
가장 마지막 학생의 수학 점수가 55점이 아니라 75점이라고 한다.

이렇게 *score* 배열을 수정하기 위한 코드를 작성하시오.

In [ ]:
### 답안을 작성하시오. 
score[-1,-3] = 75

In [ ]:
### 다음과 같이 출력되어야 한다. (수정하지 마시오.)
print(score[-1])

[21 25 75 97 45]


### 문제2
채점에 오류가 발견되어 모든 학생들의 영어점수를 2점씩 줄여야 한다고 한다. 이렇게 *score* 배열을 수정하기 위한 코드를 작성하시오.

In [ ]:
### 답안을 작성하시오. 
score[:, 1] = score[:, 1] -2

In [ ]:
### 다음과 같이 출력되어야 한다. (수정하지 마시오.)
score[0], score[-1]

(array([86, 35, 77, 67, 93]), array([21, 23, 75, 97, 45]))

### 문제3
50명의 추가 학생들의 점수가 다음 _score\_add_ 변수에 주어진다. 이를 _score_ 변수 데이터 끝에 덧붙여 100명의 데이터를 *score*변수에 다시 저장하고자 한다. 이를 위한 코드를 작성하시오.

In [ ]:
### 수정하지 마시오.
score_add=rng.randint(0, 101,(50,5))
score_add

array([[ 97,  93,  70,  58,  29],
       [ 81,  21,  16,  30,  55],
       [ 80,  30,  12,  90,  83],
       [ 16,  92,  38,  98,   7],
       [ 37,  14,   0,  96,   2],
       [ 37,  47,  62,  61,  14],
       [ 61,  81,  37,  94,  19],
       [ 58,   6, 100,  90,  71],
       [ 77,  78,  70,  96,  51],
       [ 97,   3,   0,  77,  94],
       [ 37,  52,  83,   2,  98],
       [ 96,  14,   2,  91,  90],
       [ 32,  82,  55,  32,  30],
       [  3,  95,  91,  79,  91],
       [ 78,  21,  30,  59,  84],
       [ 31,  70,  96,   7,  77],
       [ 61,  88,  95,  27,  65],
       [ 16,  90,   1,   7,  37],
       [ 19,  63, 100,  20,  89],
       [ 30,  83,  69,  14,  56],
       [  0,  89,  28,  65,  21],
       [ 60,  28,   8,  40,  20],
       [ 54,  95,  95,  39,  25],
       [ 47,  76,   2,  95,  32],
       [ 96,  41,  76,  42,  69],
       [  3,  63,  69,  50,  66],
       [ 90,  83,  17,  19,  29],
       [ 73,  51,  22,  46,   2],
       [ 49,   8,  18,  35,  39],
       [ 26,  

In [ ]:
### 답안을 작성하시오. 
score = np.concatenate([score,score_add])

In [ ]:
### 다음과 같이 출력되어야 한다. (수정하지 마시오.)
score[0], score[49], score[50], score[99]

(array([86, 35, 77, 67, 93]),
 array([21, 23, 75, 97, 45]),
 array([97, 93, 70, 58, 29]),
 array([22, 32, 46, 94, 20]))

### 문제4
과목별 평균점수를 뜻하는 _avg\_subject_ array(1차원)를 구하는 코드를 작성하시오. 

In [ ]:
### 답안을 작성하시오. 
avg_subject = score.sum(axis=0)/100

In [ ]:
### 다음과 같이 출력되어야 한다. (수정하지 마시오.)
avg_subject

array([52.87, 56.46, 53.59, 56.8 , 53.12])

### 문제5
학생별 평균점수를 뜻하는 _avg\_student_ array(1차원)를 구하는 코드를 작성하시오. 

In [ ]:
### 답안을 작성하시오. 
avg_student = score.sum(axis=1)/5

In [ ]:
### 다음과 같이 출력되어야 한다. (수정하지 마시오.)
avg_student

array([71.6, 63. , 83.4, 62.6, 53.2, 70. , 59.4, 53. , 66.4, 62.6, 65.8,
       46.8, 69.2, 40.6, 28.2, 59.8, 72.4, 47.8, 51.4, 52.2, 74.6, 56.6,
       65.6, 65. , 84.6, 52.6, 67.4, 47.8, 59.8, 70.2, 57.4, 57.2, 57.6,
       66.8, 64.4, 69.8, 37. , 59.6, 58.8, 54. , 51.8, 62.6, 63.6, 61.4,
       56.8, 53.8, 47. , 66.2, 60. , 52.2, 69.4, 40.6, 59. , 50.2, 29.8,
       44.2, 58.4, 65. , 74.4, 54.2, 54.4, 58.6, 46.2, 71.8, 54.4, 56.2,
       67.2, 30.2, 58.2, 50.4, 40.6, 31.2, 61.6, 50.4, 64.8, 50.2, 47.6,
       38.8, 29.8, 68. , 31.6, 40.8, 38.4, 57.2, 46.4, 54.2, 57.8, 59.4,
       30.2, 42.2, 58.2, 53.6, 44.6, 36.8, 41.2, 35.2, 56.2, 47.4, 25.2,
       42.8])

### 문제6
각 점수가 해당과목의 평균으로부터 얼마나 차이가 나는지(이를 편차라고 한다.)를 나타내는 _score\_dev_ array(2차원)를 생성하시오.
- score_dev의 shape는 score의 shape와 동일하다. 즉 (100, 5)
- 만약 어떤 학생의 국어 점수가 30점이고 국어 평균이 45점이면 그 차이(편차)는 $30-45=-15$ 점이다.

---
참고) _score\_dev_ 의 axis=0 방향 평균값이 어떻게 될 지 생각해 보자.


In [ ]:
### 답안을 작성하시오. 
score_dev = score-avg_subject

In [ ]:
### 다음과 같이 출력되어야 한다. (수정하지 마시오.)
score_dev[0], score_dev[-1]

(array([ 33.13, -21.46,  23.41,  10.2 ,  39.88]),
 array([-30.87, -24.46,  -7.59,  37.2 , -33.12]))

### 문제7
전체과목 평균점수를 기준으로 1등을 한 학생과 꼴등을 한 학생의 5개 과목 점수 array를 각각 *student_best*, *student_worst*에 각각 저장하시오. 

In [ ]:
### 답안을 작성하시오. 
student_best = score[avg_student.argmax()]
student_worst = score[avg_student.argmin()]

In [ ]:
### 다음과 같이 출력되어야 한다. (수정하지 마시오.)
student_best, student_worst

(array([85, 88, 60, 94, 96]), array([ 8, 25, 76, 17,  0]))

### 문제8
전체 학생의 평균점수를 구하여 _avg\_total_ 변수에 저장하시오. 

In [ ]:
### 답안을 작성하시오. 
avg_total = score.mean()

In [ ]:
### 다음과 같이 출력되어야 한다. (수정하지 마시오.)
avg_total

54.568

### 문제9
전체 평균 점수(_avg\_total_) 보다 높은 평균 점수를 얻은 학생의 수를 구하여 _no\_student\_high_ 변수에 저장하시오.  

In [ ]:
### 답안을 작성하시오. 
no_student_high = np.count_nonzero(avg_student>avg_total)

In [ ]:
### 다음과 같이 출력되어야 한다. (수정하지 마시오.)
no_student_high

52

### 문제10
과학점수가 사회점수보다 더 높은 학생 수를 구하여 _no\_student\_sci_ 변수에 저장하시오.
 

In [ ]:
### 답안을 작성하시오. 
no_student_sci = np.count_nonzero(score[:,3] > score[:, 4])

In [ ]:
### 다음과 같이 출력되어야 한다. (수정하지 마시오.)
no_student_sci

48