# Understanding Data Types in Python

## A Python List Is More Than Just a List

Python의 list는 기본적으로 dynamic-type array(Python list의 장점)이다. 

In [1]:
L3 = [True, "2", 3.0, 4] # 데이터 타입 여러개를 원소로 기입가능
[type(item) for item in L3] #List comprehension
# C에서는 같은 자료형들끼리 묶음

[bool, str, float, int]

이러한 dynamic-type array는 편리하지만 효율적이지 않다.
따라서 fixed-type array가 제공되며 NumPy array도 그렇다.

## Fixed-Type Arrays in Python

Built-in ``array`` module을 사용할 수 있다. (available since Python 3.3) 

In [2]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

여기에서 ``'i'`` 는 integer array임을 뜻한다. 

NumPy package의 ``ndarray`` object가 보다 편리하며 data science에서 배우는 이유가 된다.

In [2]:
import numpy as np

## Creating Arrays from Python Lists

``np.array``을 사용하여 Python list로부터 NumPy array를 생성할 수 있다.

In [ ]:
# integer array:
np.array([1, 4, 2, 5, 3])

Fixed-type array이어야 하므로 정수와 실수가 혼합되면 upcast된다. 

In [ ]:
np.array([3.14, 4, 2, 3])
# 정보 손실을 최소화하기 위한 방법으로 compile 됨. 대신 더 많은 메모리 소모

``dtype`` keyword를 사용하여 explicit cast 할 수도 있다.

In [3]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

또한 multi-dimensional array를 생성할 수 있다. 

In [ ]:
# nested lists result in multi-dimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

## Creating Arrays from Scratch

아래 예들과 같이 NumPy built-in 함수를 사용하여 array를 생성할 수 있다. 

In [ ]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)
#zeros = 행렬을 0으로 가득 채워라!

In [6]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.zeros((3,2,4), dtype=int)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [ ]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)
# full = 가득 채우되 지정된 숫자로

In [5]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)
# 0부터 20이 나오기전까지 간격을 2로해서 출력
# 많이 쓰는 내용

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)
# 0과 1을 다섯 등분 해라
#많이 쓰는 내용 2

In [10]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))
#.random.random = 0과 1사이의 숫자를 무작위
# uniformly(일정하다) distributed = 모든 수가 뽑힐 확률을 동일하게 설정

array([[0.12189811, 0.88805861, 0.05058886],
       [0.73092625, 0.17539136, 0.85951   ],
       [0.56488881, 0.03926012, 0.82728321]])

In [11]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))
# normally distributed = 정규분포(평균값이 높고, 가쪽으로 갈 수록 확률이 낮은 형태)
# 대표적인 예시가 키 -> 평균키가 175라면 그 키인 남자가 나올 확률이 높음. 
# 평균이 0이고 표준편자가 1

array([[ 0.54563733, -0.73036045,  1.25002642],
       [-2.61751636,  0.24819508, -0.47689012],
       [ 0.42649365, -0.8687084 , -0.61978861]])

In [12]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))
# uniformly distributed.

array([[7, 5, 8],
       [4, 8, 0],
       [8, 2, 2]])

In [13]:
# Create a 3x3 identity matrix
np.eye(3)
# 정방 행렬(1이 대각선형태, 1이 아닌 위치에는 0)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)
# 어떤 수인지는 모르겠으나 1로 초기화만 시켜놓겠다. 사이즈는 3으로..

array([1., 1., 1.])

## NumPy Standard Data Types

NumPy array의 type 종류는 아래 테이블과 같다. 
```python
np.zeros(10, dtype='int16')
```

Or using the associated NumPy object:

```python
np.zeros(10, dtype=np.int16)
```

| Data type	    | Description |
|---------------|-------------|
| ``bool_``     | Boolean (True or False) stored as a byte |
| ``int_``      | Default integer type (same as C ``long``; normally either ``int64`` or ``int32``)| 
| ``intc``      | Identical to C ``int`` (normally ``int32`` or ``int64``)| 
| ``intp``      | Integer used for indexing (same as C ``ssize_t``; normally either ``int32`` or ``int64``)| 
| ``int8``      | Byte (-128 to 127)| 
| ``int16``     | Integer (-32768 to 32767)|
| ``int32``     | Integer (-2147483648 to 2147483647)|
| ``int64``     | Integer (-9223372036854775808 to 9223372036854775807)| 
| ``uint8``     | Unsigned integer (0 to 255)| 
| ``uint16``    | Unsigned integer (0 to 65535)| 
| ``uint32``    | Unsigned integer (0 to 4294967295)| 
| ``uint64``    | Unsigned integer (0 to 18446744073709551615)| 
| ``float_``    | Shorthand for ``float64``.| 
| ``float16``   | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa| 
| ``float32``   | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa| 
| ``float64``   | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa| 
| ``complex_``  | Shorthand for ``complex128``.| 
| ``complex64`` | Complex number, represented by two 32-bit floats| 
| ``complex128``| Complex number, represented by two 64-bit floats| 